# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1ae84823f6de444bfd85a89bf63992b6e3e97f7f6e59192beb5091b5ae03fa90f649e4dd1b3f99b89b7c1016988ce12802a335a3beaafd6ccb8f4dd13dc791e

test:
  secret_key_base: b775014a3fc30c9a302e96445253379cda480c796a5f6062e3e10dfe4f88b217cf02cb64a7fbf24b7a356bf10b6819394e9bc5a48aab0e13bc84e75c71e93f41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
